final Map<String, String> thTH = {
  'account': 'บัญชีผู้ใช้',
  'settings': 'การตั้งค่า',
  'language': 'ภาษา',
  'theme': 'ธีม',
  'system': 'ตามระบบ',
  'light': 'สว่าง',
  'dark': 'มืด',
  'home': 'หน้าแรก',
  'Order': 'สั่งซื้อ',
  'order': 'สั่งซื้อ',
  'address': 'ที่อยู่',
  'stores': 'ร้านค้า',
  'scanqr': 'สแกน QR',
  'signin': 'เข้าสู่ระบบ',
  'signout': 'ออกจากระบบ',
  'welcome': 'ยินดีต้อนรับ',
  'profile': 'โปรไฟล์',
  'notifications': 'การแจ้งเตือน',
  'help': 'ช่วยเหลือ',
  'about': 'เกี่ยวกับ',
  'privacy': 'ความเป็นส่วนตัว',
  'terms': 'เงื่อนไขการใช้งาน',
  'logout': 'ออกจากระบบ',
  'login': 'เข้าสู่ระบบ',
  'register': 'ลงทะเบียน',
  'search': 'ค้นหา',
  'inbox': 'ข้อความ',
  'card': 'บัตร',
  'Pay in store': 'ชำระเงินที่ร้าน',
  'delivery': 'จัดส่ง',

  //Order Page
  'Deliver': 'จัดส่ง',
  'Find your favorite Starbucks': 'ค้นหาร้าน Starbucks',
  'In-store Pickup': 'รับที่ร้าน',
  'choose a Starbucks near you': 'เลือกร้าน Starbucks ใกล้คุณ',
  'Order to Table': 'สั่งที่โต๊ะ',
  'Scan Qr code at the table to order': 'สแกน QR โค้ดที่โต๊ะเพื่อสั่งซื้อ',
  // เพิ่ม key อื่นๆ ตามต้องการ
};
