final Map<String, String> thTH = {
  'account': 'บัญชีผู้ใช้',
  'settings': 'การตั้งค่า',
  'language': 'ภาษา',
  'theme': 'ธีม',
  'system': 'ตามระบบ',
  'light': 'สว่าง',
  'dark': 'มืด',
  'home': 'หน้าแรก',
  'Order': 'สั่งซื้อ',
  'order': 'สั่งซื้อ',
  'address': 'ที่อยู่',
  'stores': 'ร้านค้า',
  'scanqr': 'สแกน QR',
  'signin': 'เข้าสู่ระบบ',
  'signout': 'ออกจากระบบ',
  'welcome': 'ยินดีต้อนรับ',
  'profile': 'โปรไฟล์',
  'notifications': 'การแจ้งเตือน',
  'help': 'ช่วยเหลือ',
  'about': 'เกี่ยวกับ',
  'privacy': 'ความเป็นส่วนตัว',
  'terms': 'เงื่อนไขการใช้งาน',
  'logout': 'ออกจากระบบ',
  'login': 'เข้าสู่ระบบ',
  'register': 'ลงทะเบียน',
  'search': 'ค้นหา',
  'inbox': 'ข้อความ',
  'card': 'บัตร',
  'delivery': 'จัดส่ง',
  'Sign in': 'เข้าสู่ระบบ',
  'Join now': 'เข้าร่วมตอนนี้',

  //sign in page
  'Email or password is incorrect': 'อีเมลหรือรหัสผ่านไม่ถูกต้อง',
  'Email': 'อีเมล',
  'Password': 'รหัสผ่าน',
  'Show': 'แสดง',
  'Hide': 'ซ่อน',
  'Forgot password?': 'ลืมรหัสผ่าน?',
  'Stay signed in': 'อยู่ในระบบต่อไป',

  // Join Now Page
  'Enter your email': 'กรอกอีเมลของคุณ',
  'A verification link will be sent to this email':
      'ลิงก์ยืนยันจะถูกส่งไปยังอีเมลนี้',
  'A verification link will be sent to': 'ลิงก์ยืนยันจะถูกส่งไปยัง',

  // Home Page
  'It\'s a great day for coffee': 'เริ่มต้นวันใหม่ด้วยกาแฟ',
  'Find your favorite drinks and food': 'ค้นหาเครื่องดื่มและอาหารที่',
  'Find a store': 'ค้นหาร้าน',
  'Pay in\nstore': 'ชำระเงินที่ร้าน',
  'Delivery\n': 'จัดส่งถึงบ้าน',
  'In-store\nPickup': 'รับที่ร้าน',
  'Order to\nTable': 'สั่งที่โต๊ะ',
  "Getting started with Starbucks": 'เริ่มต้นกับ Starbucks*',
  "Rewards is easy": 'สะสมคะแนนได้ง่ายๆ',
  "Say hello to easy ordering, collect Stars on everything you buy and get your favorites for free.":
      'สั่งซื้อได้ง่ายๆ สะสมดาวจากทุกการซื้อและรับของโปรดฟรี',
  "Join Now": 'เข้าร่วมตอนนี้',
  'NEWS & PROMOTION': 'ข่าวสารและโปรโมชั่น',

  // Card Page
  'Welcome to Starbucks® Rewards': 'ยินดีต้อนรับสู่ Starbucks® Rewards',
  'Enjoy a cashless and convenient experience in-store and easy ordering via Starbucks® TH App. Simply join Starbucks® Rewards and unlock access to exclusive perks.':
      'เพลิดเพลินกับประสบการณ์การชำระเงินที่สะดวกสบายและการสั่งซื้อที่ง่ายดายผ่านแอป Starbucks® TH เพียงเข้าร่วม Starbucks® Rewards และปลดล็อกสิทธิพิเศษเฉพาะสมาชิก',
  'CARD BALANCE': 'ยอดคงเหลือในบัตร',
  'Manage': 'จัดการ',
  'As of 10 Jun 2025 07:02': 'วันที่ 10 มิ.ย. 2025 07:02',
  'View all cards': 'ดูบัตรทั้งหมด',
  'YOUR BENEFIT(S)': 'สิทธิประโยชน์ของคุณ',
  'You have no Benefits available': 'คุณไม่มีสิทธิประโยชน์ที่ใช้ได้',
  'Add card': 'เพิ่มบัตร',
  'Add money': 'เพิ่มเงิน',
  'Transfer': 'โอนเงิน',
  'Pay in store': 'ชำระเงินที่ร้าน',

  //Order Page
  'Say hello to easy ordering, tasty Rewards and get your favorites for free.':
      'สั่งซื้อได้ง่ายๆ สะสมดาวจากทุกการซื้อและรับของโปรดฟรี',
  'Deliver': 'จัดส่ง',
  'Find your favorite Starbucks': 'ค้นหาร้าน Starbucks',
  'In-store Pickup': 'รับที่ร้าน',
  'choose a Starbucks near you': 'เลือกร้าน Starbucks ใกล้คุณ',
  'Order to Table': 'สั่งที่โต๊ะ',
  'Scan Qr code at the table to order': 'สแกน QR โค้ดที่โต๊ะเพื่อสั่งซื้อ',
  'Exclusive for Starbucks® Rewards members.':
      'เฉพาะสมาชิก Starbucks® Rewards เท่านั้น',
  // Inbox Page
  'Inbox': 'กล่องข้อความ',
  'Edit': 'แก้ไข',
  'Enjoy Starbucks beverages – only 140 Baht!':
      'เพลิดเพลินกับเครื่องดื่ม Starbucks – เพียง 140 บาท!',
  '09 Jun 2025': '09 มิ.ย. 2025',
  'Refresh Alert': 'แจ้งเตือนการรีเฟรช',
  '04 Jun 2025': '04 มิ.ย. 2025',
  'Earn Double Stars': 'รับดาวสองเท่า',
  'Earn 7 Bonus Stars': 'รับโบนัสดาว 7 ดวง',
  '26 May 2025': '26 พ.ค. 2025',
  'Happy Specials! Only 125 Baht': 'โปรโมชั่นพิเศษ! เพียง 125 บาท',
  '19 May 2025': '19 พ.ค. 2025',
  'Get 1 Bonus Star': 'รับโบนัสดาว 1 ดวง',
  '15 May 2025': '15 พ.ค. 2025',
  '28 Apr 2025': '28 เม.ย. 2025',

  //Account Page
  'ACCOUNT DETAILS': 'รายละเอียดบัญชี',
  'Your mobile order(s)': 'คำสั่งซื้อของคุณ',
  'My credit / debit cards': 'บัตรเครดิต / บัตรเดบิตของฉัน',
  'Delivery address': 'ที่อยู่จัดส่ง',
  'Personal information': 'ข้อมูลส่วนตัว',
  'Starbucks® Rewards': 'รางวัล Starbucks®',
  'SETTINGS': 'การตั้งค่า',
  'General': 'ทั่วไป',
  'Security': 'ความปลอดภัย',
  'Language': 'ภาษา',
  'ABOUT': 'เกี่ยวกับ',
  'FAQs': 'คำถามที่พบบ่อย',
  'Terms of use': 'เงื่อนไขการใช้งาน',
  'Privacy policy': 'นโยบายความเป็นส่วนตัว',
  'Feedback': 'ข้อเสนอแนะแนวทาง',
  'Tell a friend': 'บอกเพื่อน',
  'Delete account': 'ลบบัญชี',
  'Sign out': 'ออกจากระบบ',
  'App version 7.2.4': 'เวอร์ชันแอป 7.2.4',
  'Sign me out': 'ออกจากระบบ',
  'Are you sure you want to sign out?': 'คุณแน่ใจหรือไม่ว่าต้องการออกจากระบบ?',

  //pay in store screen
  'Pay': 'ชำระเงิน',
  'Change': 'เปลี่ยน',
  //'CARD BALANCE': 'ยอดคงเหลือในบัตร', มีแล้วใน Card Page
  'As of 23 Jun 2025 19:43': 'ณ วันที่ 23 มิ.ย. 2025 19:43',
  'Please tell a barista to redeem the reward': 'กรุณาบอกบาริสต้าก่อนใช้รางวัล',
  //'YOUR BENEFIT(S)': 'สิทธิประโยชน์ของคุณ', มีแล้วใน Card Page

  //Delivery Page
  'Search for location': 'ค้นหาสถานที่',
  'Enter a building or a street name': 'กรอกชื่ออาคารหรือถนน',
  'RECENT SEARCHES': 'การค้นหาล่าสุด',
  'Select a Store': 'เลือกสาขา',
  'Nearby Stores': 'ร้านค้าใกล้เคียง',
};
